Neural Networks Deep Learning
Python & Vectorization

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time

#vectorized
a= np.random.rand(1000000) #million dimension array
b = np.random.rand(1000000)

tic = time.time()
c= np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version " + str(1000*(toc-tic))+ ' ms')

#average of 1.5 ms

#non-vectorized
c=0
tic = time.time()
for i in range(1000000):
    c+= a[i]*b[i]
toc = time.time()
print(c)
print("For loop "+ str(1000*(toc-tic))+ ' ms')

#vectorize your code fro 300x faster!

#scalable on a GPU - jupyter has CPU (SIMD parellization)

249873.844445
Vectorized version 1.6031265258789062 ms
249873.844445
For loop 493.82495880126953 ms


In [13]:
#neural network programming guideline

#Avoid explicit for-loops

#example - exponential on matrices
import math
n = 5
y = a
u = np.zeros((n,1))
for i in range(n):
    u[i] = math.exp(y[i])
v = a    
#v input vector    
u = np.exp(v)
s = np.log(v)
t = np.maximum(v,0)
print(u,s,t)


[ 1.92992378  1.93919724  2.01066409 ...,  2.6067835   1.15838077
  1.41219033] [-0.41934016 -0.41207577 -0.35887012 ..., -0.04278529 -1.91716528
 -1.06379958] [ 0.65748051  0.66227409  0.69846506 ...,  0.95811708  0.14702314
  0.34514192]


In [14]:
# vectorizing logistic regression

# z(i) = w(t)*x(i) + b
# broadcasting
# Z = np.dot(w.T,X) + b 

#sigmoid function
# a(i) = sigma*(z(i))
# A = sigma(Z)

In [15]:
#vectorizing logistic regression gradient ouput

#dz(i) = a(i) -y(i)
#dZ = A - Y

#dw, dz = 0,0
#dw += x(i)*dz(i)
#dw /= m
#db += dz(i)
#db /= m

#db = 1/m*np.sum(dZ)
#dw = 1/m*X*dZ.T

# w = w - alpha*dw
# b = b - alpha*db



In [25]:
#broadcasting

A = np.array([[56, 0, 44, 68],
              [12, 104, 52, 8],
              [18, 135, 99, 9]])
print(A)
cal = A.sum(axis = 0) #vertical sum
print(cal)

percentage = 100*A/(cal.reshape(1,4)) #(3,4) / (1,4)
print(percentage)

[[ 56   0  44  68]
 [ 12 104  52   8]
 [ 18 135  99   9]]
[ 86 239 195  85]
[[ 65.11627907   0.          22.56410256  80.        ]
 [ 13.95348837  43.51464435  26.66666667   9.41176471]
 [ 20.93023256  56.48535565  50.76923077  10.58823529]]


In [26]:
#python-numpy

a = np.random.randn(5)
print(a)

[ 1.61461881 -1.29841736  0.9954571   0.19275036  1.0875973 ]


In [27]:
print(a.shape) #rank 1 array - don't use these data structures

(5,)


In [28]:
print(a.T)

[ 1.61461881 -1.29841736  0.9954571   0.19275036  1.0875973 ]


In [29]:
print(np.dot(a,a.T))

6.50383694594


In [30]:
a = np.random.randn(5,1) #column vector
print(a)

[[-1.86656036]
 [ 0.17898634]
 [-1.51861372]
 [-0.10453277]
 [ 0.45712754]]


In [31]:
print(a.T) #row vector

[[-1.86656036  0.17898634 -1.51861372 -0.10453277  0.45712754]]


In [32]:
print(np.dot(a,a.T)) #matrix!

[[ 3.48404758 -0.33408881  2.83458418  0.19511672 -0.85325615]
 [-0.33408881  0.03203611 -0.27181112 -0.01870994  0.08181959]
 [ 2.83458418 -0.27181112  2.30618764  0.15874489 -0.69420015]
 [ 0.19511672 -0.01870994  0.15874489  0.0109271  -0.04778481]
 [-0.85325615  0.08181959 -0.69420015 -0.04778481  0.20896559]]


In [33]:
#assertion statements

assert(a.shape == (5,1))
a = a.reshape((5,1))

In [ ]:
#n,1 or 1,n matrices, double check dimensions, use reshape